version : "2"

services:
  ezgo:
    image: ezgo:latest
    ports:
    - "8000:8000"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
